SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 24873)
-- Name: preferiti; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.preferiti (
    id_cliente integer NOT NULL,
    id_ristorante integer NOT NULL
);


ALTER TABLE public.preferiti OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24850)
-- Name: recensioni; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recensioni (
    id_cliente integer NOT NULL,
    id_ristorante integer NOT NULL,
    id_recensione integer NOT NULL,
    username character varying NOT NULL,
    voto integer NOT NULL,
    testo character varying NOT NULL,
    risposta character varying
);


ALTER TABLE public.recensioni OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24890)
-- Name: recensioni_id_recensione_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recensioni ALTER COLUMN id_recensione ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recensioni_id_recensione_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24819)
-- Name: ristoranti; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ristoranti (
    id_ristorante integer NOT NULL,
    nome character varying NOT NULL,
    indirizzo character varying NOT NULL,
    delivery boolean NOT NULL,
    prenotazione_online boolean NOT NULL,
    tipo_cucina character varying NOT NULL,
    prezzo character varying(5) NOT NULL,
    descrizione character varying NOT NULL,
    latitudine double precision NOT NULL,
    longitudine double precision NOT NULL,
    proprietario integer NOT NULL
);


ALTER TABLE public.ristoranti OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24818)
-- Name: ristoranti_id_ristorante_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ristoranti ALTER COLUMN id_ristorante ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ristoranti_id_ristorante_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16619)
-- Name: utenti; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utenti (
    id_utente integer CONSTRAINT utenti_id_not_null NOT NULL,
    nome character varying NOT NULL,
    cognome character varying NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    data_nascita date NOT NULL,
    indirizzo character varying NOT NULL,
    ruolo character varying NOT NULL,
    latitudine double precision NOT NULL,
    longitudine double precision NOT NULL
);


ALTER TABLE public.utenti OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16618)
-- Name: utenti_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utenti ALTER COLUMN id_utente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utenti_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5039 (class 0 OID 24873)
-- Dependencies: 224
-- Data for Name: preferiti; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.preferiti VALUES (4, 2);


--
-- TOC entry 5038 (class 0 OID 24850)
-- Dependencies: 223
-- Data for Name: recensioni; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.recensioni VALUES (4, 2, 1, 'antonino', 4, 'molto buono, tornerò ', 'sono felice che ti sia piaciuto ');


--
-- TOC entry 5037 (class 0 OID 24819)
-- Dependencies: 222
-- Data for Name: ristoranti; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.ristoranti VALUES (2, 'Le Calandre', 'via Liguria 1, località Sarmeola, Rubano, 35030, Italy', false, false, 'CINESE', '€€€€', 'Situated away from the main road and the main shopping centre, the fabulous Le Calandre is run by the Alajmo family. The soft lighting (even during the day) perfectly complements the decor in the minimalist-style dining room designed by brothers Massimiliano and Raffaele (as is most of the tableware used in the restaurant). The cuisine is presented on three tasting menus (Classico, Max and Raf), with the option of reducing the number of courses and choosing dishes from different menus, almost à la carte style. With its combination of familiar flavours and imaginative twists, Max’s cuisine celebrates the restaurant’s signature dishes such as the “passi d’oro” 2.0 risotto and the famous cuttlefish cappuccino in black ink, as well as creative dishes inspired by the passing seasons. The restaurant also has its own delicatessen for anyone keen to purchase a gourmet souvenir.', 45.4215425, 11.8096633, 2);
INSERT INTO public.ristoranti VALUES (3, 'Uliassi', 'banchina di Levante 6, Senigallia, 60019, Italy', true, true, 'ITALIANA', '€€€€', 'The Adriatic Riviera, a perfect picture-postcard summer holiday destination, is the setting for this fine restaurant run by chef Mauro Uliassi. Hidden among the private beach clubs that crowd Senigallia’s seafront, this three-Michelin-star restaurant comes as a surprise, surrounded as it is by beach parasols and the sound of the sea lapping on the shore. The strength and originality of Uliassi’s cuisine lies in his ability to make good use of local ingredients, taking inspiration from the culinary traditions that have been so familiar and successful along this coastline over the past few decades and giving them a personal, creative twist. Fish and seafood obviously take pride of place, although there’s also room on the menu for meat, inspired by the Marche’s traditional game dishes – the delicious skewered pigeon is cooked to perfection! The colourful dining experience here is enhanced by the owner’s warm welcome, with Mauro’s sister Catia and his son Filippo working alongside the chef. It’s also worth mentioning that the restaurant has a keen focus on the environment, hence its banning of the use of plastic and doing its utmost to persuade its fish suppliers not to use polystyrene to transport their fish.', 43.7194609, 13.2206503, 2);
INSERT INTO public.ristoranti VALUES (4, 'Enoteca Pinchiorri', 'via Ghibellina 87, Florence, 50122, Italy', true, false, 'GIAPPONESE', '€€€€', 'The cuisine at Pinchiorri is striking for its opulent and grandiose style which impresses without becoming overly fussy or excessive, so that the main focus in every dish is the flavour of its ingredients. The magnificent feast of courses resembles a firework display, with each course more impressive than the last in a growing crescendo of delights. It’s worth coming here simply to experience the service, an impeccable waltz directed by Alessandro Tomberli, one of the best maître-d’s in Italy. Annie Féolde, one of the restaurant’s icons, left the reins to the highly talented chef Riccardo Monco, who continues to nurture and satisfy the Italian appetite for fine cuisine. Credit must also go to Giorgio Pinchiorri, who has developed a wine list that is renowned across the globe.', 43.770066, 11.2621974, 3);
INSERT INTO public.ristoranti VALUES (5, 'Villa Crespi', 'via Fava 18, Orta San Giulio, 28016, Italy', true, false, 'VEGETARIANA', '€€€€', 'Just a stone’s throw from the enchanting village of Orta San Giulio with its picture-postcard views of the lake and San Giulio island, this three-Michelin-star restaurant boasts a stunning location in a late-19C Moorish-style villa. Impressive both inside and out, this aristocratic residence was once the home of the Crespi family. Today, the villa’s leading light is Antonino Cannavacciuolo, who is now at the helm of a number of Michelin-starred restaurants, of which the Villa Crespi, the most famous and celebrated of them all, is the flagship. Although this chef originally from Vico Equense in Campania takes inspiration from all over Italy and further afield, it is the passion, colour and intense flavours of his native region that shine through in all his dishes. The two tasting menus, as well as the concise à la carte, showcase elegant dishes full of goodness where the focus is on fish and seafood (although meat also features). This is Mediterranean cuisine in all its glory, with a contemporary style that is never forced – typical of Cannavacciuolo at his very best.', 45.7964778, 8.4159486, 2);
INSERT INTO public.ristoranti VALUES (6, 'Quattro Passi', 'via Vespucci 13/n, Marina del Cantone, 80061, Italy', false, true, 'INDIANA', '€€€€', 'This restaurant’s 40-year history began with present owner-chef Fabrizio Mellino’s grandfather, who ran a small business selling eggs from his own hens. From this, he decided to branch out and open a pizzeria “four steps from the sea” (hence the name Quattro Passi), which over the years his son Antonio and now his grandson Fabrizio have transformed into a temple to Mediterranean cuisine. Flavours, strong technique and quality ingredients combine to create an exciting feast for the tastebuds which finishes with a selection of small chocolate eggs with unusual flavours such as roquefort, rocket, chilli pepper and lemon. A host of different influences (the sea, the Sannio region, France, Japan) and ingredients (San Marzano tomatoes, Amalfi lemons) come together in Fabrizio’s cuisine, resulting in dishes that are simple, delicious and full of flavour. It’s not an easy journey to Marina del Cantone, but once here you’ll be warmly welcomed by Raffaele and his team, after which you can sit back and enjoy a truly memorable dining experience.', 40.5857091, 14.3537561, 2);
INSERT INTO public.ristoranti VALUES (7, 'La Pergola', 'via Cadlolo 101, Rome, 00136, Italy', true, false, 'AMERICANA', '€€€€', 'Following complete refurbishment, the new Pergola pays tribute to the colours and materials of Rome, from the Travertine marble to the red colour scheme. The terrace has also had a face-lift, but fortunately the view hasn’t changed – however many times you come here, you find that your memory never quite does justice to the magnificent and expansive views of the capital. Below Monte Mario hill, the whole of Rome, encircled by hills, is spread out before you, appearing silent and enchanted, almost as if it were dozing. Although he’s been at the helm here since 1994, Heinz Beck’s enthusiasm remains undiminished, as he continues to update his dishes, explore new avenues and create imaginative cuisine with a strong Italian and Mediterranean flavour. In addition to the spectacular wine list, there’s also a remarkable choice of water and coffee.', 41.9187946, 12.4461151, 2);
INSERT INTO public.ristoranti VALUES (8, 'Reale', 'contrada Santa Liberata, località Casadonna, Castel di Sangro, 67031, Italy', false, false, 'VEGETARIANA', '€€€€', 'Housed in a 16C monastery amid gardens and vineyards in the foothills surrounding Castel di Sangro, this restaurant boasts a simple, minimalist style which is echoed in its cuisine, created by one of the most easily identified and recognisable chefs in Italy. For years, Niko Romito has been renowned for his minimalist-style dishes which are prepared from just a few ingredients, featuring sauces with an Italian rather than classically French flavour, and this remarkable chef continues to research and evolve. He focuses on ingredients and recipes from his native Abruzzo, paying particular attention to vegetables and creating dishes that are striking for their intense flavours. As ever, his dishes are apparently simple yet often the result of complex preparation that leaves his guests full of spellbound admiration.', 41.7800349, 14.094554, 1);
INSERT INTO public.ristoranti VALUES (9, 'Da Vittorio', 'via Cantalupa 17, Brusaporto, 24060, Italy', false, false, 'VEGANA', '€€€€', 'Although there’s an à la carte at this welcoming, family-run restaurant, the four tasting menus served here are the highlight: “Gli esordi di papà Vittorio” (traditionally inspired meat dishes); “Dalla nostra campagna” (vegetables grown in the restaurant’s own kitchen garden and at Planet Farm); “Carta Bianca” (16 courses showcasing the chef’s creative skills to the full); and “Nella tradizione di Vittorio"" (8 fish and seafood courses prepared with fresh produce from the market, including the famous “pacchero” or mantis shrimp). All the dishes are prepared using carefully chosen, top-quality ingredients and are striking for their beautiful presentation and rich, intense and traditional flavours. At Vittorio, guests are carefully looked after from start to finish, with the extraordinary cheese and dessert trolleys providing a fitting finale.', 45.6756778, 9.7692511, 3);
INSERT INTO public.ristoranti VALUES (10, 'Osteria Francescana', 'via Stella 22, Modena, 41121, Italy', false, false, 'INDIANA', '€€€€', 'Situated in Via Stella, this restaurant eschews an overly ornate decor in favour of a simpler, more contemporary and elegant style which is enhanced by striking works of art (Massimo Bottura is a passionate art enthusiast). This understated style is echoed in the cuisine, where grandiose gestures are replaced by a balanced approach which pays careful attention to every detail. The menu has a broad reach, including specialities from Modena and Emilia (ingredients such as Parmesan cheese, balsamic vinegar and tagliatelle and tortellini pasta), as well as classic international dishes, which the chef reinterprets with a light and playful touch, reminding us that food should not be a boring ritual but instead an enjoyable experience influenced by memory and culture. The impressive wine list includes lesser-known labels from small-scale producers with interesting stories, as well as top-quality options from established wineries.', 44.6448099, 10.9215518, 2);
INSERT INTO public.ristoranti VALUES (11, 'Dal Pescatore', 'località Runate 15, Runate, 46013, Italy', false, true, 'GIAPPONESE', '€€€€', 'Having held three Michelin stars since 1996 (an Italian record), this restaurant is situated in the village of Runate which lies between Cremona and Mantova and has just a few dozen inhabitants. Now close to celebrating half a century in business, Dal Pescatore is run by an extraordinary couple who have transformed what was an old family inn into a temple of elegance and hospitality. Antonio Santini oversees the front of house, while his wife Nadia is at the helm in the kitchen, aided by sons Giovanni and Alberto. In a setting boasting an elegant mix of old and new, where space, light and colours combine to create an enchanting ambience, enjoy memorable dishes that have evolved over the decades, improving year after year without ever succumbing to modern trends so that the focus is always on flavour and the joy of good food. Dal Pescatore boasts a fairy-tale setting, occupying a delightful country house in the Parco dell’Oglio.', 45.1712728, 10.3565788, 2);
INSERT INTO public.ristoranti VALUES (12, 'Piazza Duomo', 'vicolo dell''Arco 1, angolo piazza Risorgimento 4, Alba, 12051, Italy', true, false, 'ITALIANA', '€€€€', 'A distinctive red door marks the entrance to this temple of Italian cuisine. Once inside, make your way to the first floor, where you’re greeted by pink walls and a fresco by Francesco Clemente, as well as the restaurant’s friendly front-of-house staff. Here, the individual cuisine of chef Enrico Crippa takes centre stage on three tasting menus, with a fourth shorter menu available at lunchtime. One of the menus is inspired by the vegetable gardens and the seasons, another by the region, while the third takes guests on a culinary journey through Italy and further afield. What is obvious in every single, delicious bite is the chef’s passion for plants, with vegetables, flowers, wild and cultivated herbs harvested daily all featuring in memorable, beautifully presented dishes. The iconic appetisers featuring countless delicious ingredients are a feast for the eyes and the tastebuds alike and were particularly enjoyed by our inspectors. It hardly needs mentioning that this region is passionate about wine, so it’s not entirely surprising that the restaurant offers three different wine lists: Solopiemonte pays superb homage to the region, while Tuttoilresto (divided into two options, white and red) is a celebration of French wines. The efficient and enthusiastic serving staff succeed in taking good care of guests without being excessively formal, so that three hours (roughly the amount of time you need to allow for your meal) pass almost without noticing. The chef adds the finishing touch by bidding a discreet and friendly farewell at the end of the meal.', 44.7005555, 8.0359341, 3);
INSERT INTO public.ristoranti VALUES (13, 'Arnolfo', 'viale della Rimembranza 24, Colle di Val d''Elsa, 53034, Italy', false, true, 'ITALIANA', '€€€€', 'With sharp lines created by the use of iron and glass, this modern building is especially designed to allow guests to admire the views from wherever they’re sitting. To the rear of the dining room, the large open-view kitchen framed by a superb yellow Siena marble wall is home to chef Gaetano Trovato (Mentor Chef Award 2024) and his team. Although there are three tasting menus available, one of which is vegetarian, any of the courses can also be chosen à la carte style. We could say so much about Arnolfo’s cuisine, but we’ll limit ourselves to mentioning the bread (which has been central to this chef’s work from the very beginning), duck, Chianina beef, Valdarno chicken and the ice-cream which always features among the desserts. Our inspector particularly enjoyed the delightful amuse-bouche with which guests are welcomed, the caponata with Taggiasca olives and basil, and the mullet served with white asparagus, peas and mint. The wine list is impressive, both for its quality and for the extensive selection of wines not only from Italy and France but also from other countries around the world – 7,000 different labels in total.', 43.4221, 11.1165, 3);
INSERT INTO public.ristoranti VALUES (14, 'Duomo', 'via Cap. Bocchieri 31, Ragusa, 97100, Italy', true, true, 'MESSICANA', '€€€€', 'Chef Ciccio Sultano provides an intimate portrait of Sicily at this restaurant situated just a stone’s throw from the Duomo di San Giorgio in the heart of Ibla, one of the most charming historic centres in Sicily. Drawing on his deep knowledge of the region, he creates some of the island’s most spectacular cuisine, which is served in comfortable, intimate dining rooms. There are two tasting menus, from which dishes can also be chosen à la carte. We highly recommend the pasta with sea urchin, chard and hazelnuts.', 36.9267762, 14.7408182, 2);
INSERT INTO public.ristoranti VALUES (15, 'Harry''s Piccolo', 'piazza Unità d''Italia 2, Trieste, 34121, Italy', true, false, 'VEGANA', '€€€€', 'Thanks to its hushed ambience, Harry’s Piccolo is an ideal choice for a romantic dinner or a business meal, with fine cuisine prepared by chefs Matteo Metullio and Davide De Pra (Passion Dessert Award 2024). Despite their youth, these two chefs demonstrate plenty of ability and creativity, serving dishes that showcase local meat, fish and seafood, and seasonal vegetables, as well as hints of the Orient, in this elegant setting. Memorable dishes include the tagliatelle with mussel water, saffron, sea urchins and wild fennel, and desserts such as the sesame ice cream with pepper cream and a touch of dashi. The wine list focuses particularly on the region, while also featuring some top-quality labels from outside Italy including a good selection of sparkling wines such as the renowned Krug champagne. Added bonuses are the friendly service, and an outdoor space for an aperitif or after-dinner drink with views of one of Italy’s most beautiful squares.', 45.6497242, 13.7675069, 3);
INSERT INTO public.ristoranti VALUES (16, 'Torre del Saracino', 'via Torretta 9, Vico Equense, 80069, Italy', false, true, 'MESSICANA', '€€€€', 'From the coast road you take a series of hairpin bends down to Marina di Equa, the beach at Vico, where you will see this old fortified tower standing just a few metres from the sea. In the tower itself, with music playing in the background, guests can savour an aperitif accompanied by an extraordinary selection of imaginative antipasti that offer an introduction to the excellent cuisine that awaits. From here, you move into one of two dining elegant dining rooms decorated in vintage 1970s style which look out at Vesuvius and the Bay of Naples – the setting for a meal that will linger long in the memory. Gennaro Esposito is one of the best chefs in Campania, creating beautifully presented dishes of meat and fish (often in the same dish) that are not only delicious but also full of the colour and vitality of his region.', 40.6606947, 14.419559, 1);
INSERT INTO public.ristoranti VALUES (17, 'Agli Amici', 'via Liguria 252, Godia, 33100, Italy', true, true, 'MESSICANA', '€€€€', 'Serving signature cuisine, Agli Amici is one of the leading restaurants in Friuli-Venezia Giulia, a border region of diverse cultural influences that is teeming with top-quality ingredients. Many of these are showcased on the two tasting menus (one of which is vegetarian), from which guests can also choose individual dishes à la carte. Owner-chef Emanuele Scarello makes full use of the array of ingredients from the region’s pastureland, mountains and vegetable gardens, which he transforms into culinary works of art. His interesting use of Godia potatoes involves a modern reinterpretation of a local butter and sage dish using roots, apple and fermented turnips. Front of house, Michela is responsible for a young, close-knit and professional team of staff.', 46.1021988, 13.2661162, 2);
INSERT INTO public.ristoranti VALUES (18, 'Caino', 'via della Chiesa 4, Montemerano, 58014, Italy', false, false, 'VEGETARIANA', '€€€€', 'Standing in the centre of a charming Tuscan village, Caino is at the epicentre of the cuisine of the Maremma, where Valeria Piccini is its proudest ambassador. This skilful chef sources the best ingredients from the region and then extracts every ounce of flavour from them, as demonstrated by the cacio cheese ravioli in beetroot cream and the pici pasta “alla amatriciana”. If you’re a fan of fish and seafood, try the stew which is made using delicately flavoured fish and a cream sauce, and served with blanched seasonal vegetables and traditional Tuscan crostino. Front of house, Valeria is ably assisted by son Andrea, who oversees the well-stocked wine cellar featuring a selection of different Brunello and Barolo vintages, as well as Bordeaux-style Tuscan labels, all at excellent prices. And if you’re in company, make sure you share a good Vin Santo Occhio di Pernice from 1988 or 1989. In summer, the bistro-style Il Giardino di Caino opens on the terrace, serving simpler dishes inspired by old family traditions.', 42.6220221, 11.4906283, 1);
INSERT INTO public.ristoranti VALUES (19, 'La Madia', 'corso Filippo Re Capriata 22, Licata, 92027, Italy', false, true, 'VEGANA', '€€€€', 'Park in one of the streets near this restaurant and prepare yourself for a delightful journey through Sicily and its culinary traditions! Chef Pino Cuttaia, who is demonstrably in love with his native island, highlights his ingredients in a simple and unfussy way. He uses contemporary techniques, such as in the extremely light mozzarella and tomato dish served at the beginning of the meal, as well as more traditional methods evident in the black Nebrodi suckling pig served with a tomato-based “sugo della Domenica” (Sunday gravy). The two small dining rooms with a modern and minimalist feel offer an attractive setting for this enjoyable culinary experience. Wine-enthusiasts will appreciate the interesting selection of labels (including large bottles popular with connoisseurs). We recommend the 2019 Baglio Cristo di Campobello Adènzia, a red wine with earthy notes and delightful finesse.', 37.1070131, 13.9338055, 3);
INSERT INTO public.ristoranti VALUES (20, 'Campo del Drago', 'Località Castiglion del Bosco, Montalcino, 53024, Italy', true, false, 'VEGETARIANA', '€€€€', 'A certain amount of patience is required to get to this restaurant accessed via a dusty yet attractive dirt track that wends its way through typical Tuscan landscapes. On arrival, you’ll find an enchanting village of medieval origin with a tower and an old, frescoed church, where the Rosewood Castiglion del Bosco (awarded 3 Michelin keys) offers excellent service, splendid guestrooms and one of the best restaurants in the region. Here, chef Matteo Temperini serves some of the most interesting and creative dishes in Tuscany, many of which are prepared using vegetables from the hotel’s own kitchen garden, all showcased on three tasting menus and an à la carte from which a minimum of three courses must be chosen. Dishes are served in an elegant, contemporary-style dining room with a panoramic terrace, while the wine list features over 700 labels with a focus on the region – plenty of Brunellos, plus a particularly noteworthy 2016 Sasso al Sole, also available by the glass.', 43.08386, 11.422479, 2);
INSERT INTO public.ristoranti VALUES (21, 'Castel fine dining', 'vicolo dei Castagni 18, Tirol, 39019, Italy', true, true, 'AMERICANA', '€€€€', '180° views of the Val Venosta provide the theatrical setting for chef Gerhard Wieser’s precise, technical cuisine at this restaurant, where the tasting menu changes with the seasons and focuses on the region, with the exception of a few ingredients such as the Sicilian scampi which offer an exquisite alternative to the meat dishes on offer here. Highlights include the local, organic suckling pig ravioli served with parmesan foam and three types of pepper (Szechuan, South Tyrolean and Indian) which add an original flavour to the dish. Talented sommelier Ivana is on hand to help with wine choices, paying careful attention to guests’ individual preferences, while praise is also due to Florian and his staff for their excellent service.', 46.6862223, 11.1568653, 1);
INSERT INTO public.ristoranti VALUES (22, 'Villa Feltrinelli', 'via Rimembranza 38/40, Gargnano, 25084, Italy', false, false, 'VEGANA', '€€€€', 'Villa Feltrinelli was the lakeside holiday home of the Milanese family of the same name, who chose this beautiful location on Lake Garda for its scenery of rugged mountains and its relaxing ambience. Today, over a century later, this beautiful setting is home to a luxury hotel and restaurant. Sip an aperitif on the lakeside, then move to the beautiful terrace or elegant dining room to enjoy Stefano Baiocco’s surprise tasting menu which features freshwater fish, seafood and the finest cuts of Italian meat, all expertly prepared and skilfully flavoured with different aromatic herbs. In short, this restaurant has it all – timeless appeal, striking architecture and breathtaking beauty.', 45.693253, 10.669477, 2);
INSERT INTO public.ristoranti VALUES (23, 'Il Pagliaccio', 'via dei Banchi Vecchi 129/a, Rome, 00186, Italy', false, false, 'CINESE', '€€€€', 'From its location in the heart of Rome, this restaurant takes guests on a culinary journey across the globe, with a focus on Asia and Japan in particular. Anthony Genovese blends influences from his experiences and travels to astonishing effect on two tasting menus – one dedicated to recipes that have become his signature dishes over the years, the other featuring new creations, all served in a quiet, elegant setting where excellent service is the order of the day. When the restaurant is open at lunchtime (on Saturdays), there’s also a shorter tasting menu, while if you want a longer and more private experience, you can book the Parallelsmenu served in a small room for a maximum of six guests.', 41.89793, 12.4673729, 3);
INSERT INTO public.ristoranti VALUES (24, 'Santa Elisabetta', 'piazza Santa Elisabetta 3, Florence, 50122, Italy', false, false, 'GIAPPONESE', '€€€€', 'Thought to date back to Byzantine times, the Torre della Pagliazza has had many uses over the centuries, including housing a women’s prison in the 12C. Today it is home to one of the most interesting gourmet restaurants in Florence, where chef Rocco De Santis creates imaginative Mediterranean cuisine which is precise and full of flavour, with influences from his native Campania and an emphasis on fish and seafood. At lunchtime, a tasting menu of just three courses (“Carte Blanche”) is also available. As there are just a few tables here, guests are advised to book well in advance.', 43.7717322, 11.2558883, 3);
INSERT INTO public.ristoranti VALUES (25, 'San Domenico', 'via Sacchi 1, Imola, 40026, Italy', true, false, 'AMERICANA', '€€€€', 'Although the kitchens have been recently updated with the latest equipment and a chef''s table (“Saletta 22”) which allows guests to admire the chefs at work, San Domenico has retained its timeless charm – from the almost English-style ambience of its dining rooms to the outdoor tables overlooking an attractive square with public gardens in the historic centre. This setting provides the perfect backdrop for Massimiliano Mascia’s cuisine, which includes a selection of local and Italian dishes, all prepared simply, without excessive frills and with a focus on flavour and guest satisfaction that avoids modern trends. The extensive wine list offers an array of excellent labels, including a section dedicated exclusively to rare bottles produced before 1985!', 44.3557172, 11.7124431, 1);
INSERT INTO public.ristoranti VALUES (26, 'La Peca', 'via Alberto Giovanelli 2, Lonigo, 36045, Italy', true, true, 'VEGETARIANA', '€€€€', 'Overlooking attractive rolling hills, La Peca has long been a bastion of top-quality cuisine full of strong and decisive flavours, which aims to satisfy the palate without resorting to unnecessary frills. The extensive selection includes tasting menus and an à la carte, making it impossible to list all the dishes we found memorable. However, special mention should go to the Laguna Veneta seafood antipasto, as well as the extraordinary risotto with guinea fowl, leeks and Garganega grape must, and the classic wholewheat bigoli pasta with anchovies, featuring the creative addition of red onion ice-cream, marinated anchovies and anchovy crostini. The main dishes include the excellent mallard duck, as well as fish such as barbecued eel with radicchio, apple and horseradish. The restaurant has always been strong on desserts, serving memorable options such as a reinterpreted cassata, Mont Blanc and an extraordinary choice of ice-creams and sorbets. The impressive wine cellar features around 2 000 different labels.', 45.3848934, 11.3990641, 3);
INSERT INTO public.ristoranti VALUES (27, 'daní maison', 'via Montetignuso 4, Ischia, 80077, Italy', true, true, 'AMERICANA', '€€€€', 'This aptly named restaurant (At Nino’s house) is situated in chef Nino Di Costanzo’s own house in a residential district amid the hills of Ischia. Once over the threshold, you make your way through a garden planted with a variety of Mediterranean maquis shrubs and flowers, where aperitifs and post-dinner drinks are served in the evening. There are just a few tables in the dining room, which is crowned by a typical vaulted ceiling and where guests wishing to watch the chef at work can take a seat right in front of the kitchen. The dishes here are extremely elaborate, technical and sophisticated, perfect for anyone who loves concept-based cuisine with occasionally surprising results, including in presentation. If you’re coming here by car, take care on the last stretch of road which is particularly narrow.', 40.7302578, 13.9487527, 1);
INSERT INTO public.ristoranti VALUES (28, 'Enoteca La Torre', 'lungotevere delle Armi 22/23, Rome, 00195, Italy', false, true, 'VEGETARIANA', '€€€€', 'Situated within the aristocratic Hotel Villa Laetitia with its fine architecture dating from 1911, this restaurant occupies a magnificent dining room adorned with stucco and columns, with splendid windows overlooking the exclusive garden – the perfect setting for a special occasion. Chef Domenico Stile has not forgotten his native Campania, which features in many of his dishes (from the Tarallo crackers to the baba dessert), alongside more creative influences from Italy and further afield.', 41.916491, 12.4693268, 2);
INSERT INTO public.ristoranti VALUES (29, 'Taverna Estia', 'via Guido De Ruggiero 108, Brusciano, 80031, Italy', false, true, 'FAST_FOOD', '€€€€', 'An aromatic herb garden greets visitors to this restaurant, followed by jasmine-covered alcoves that provide the perfect setting for a romantic dinner in fine weather or, if you prefer to eat indoors, an elegant dining room with a wine cellar and open-view kitchen. The restaurant is run by brothers Mario and Francesco Sposito (the former front of house, the latter in the kitchen), who together keep alive the soul of the restaurant that they inherited from their parents. They have also improved the quality so that the restaurant’s reputation now extends well beyond the region. Choose from different tasting menus (from which dishes can be chosen à la carte if you prefer) featuring remarkable and exciting dishes influenced by the flavours of Campania. More than a thousand wines, including an impressive choice of French labels, complete the picture.', 40.9083323, 14.4232938, 3);
INSERT INTO public.ristoranti VALUES (30, 'Krèsios', 'via San Giovanni 59, Telese, 82037, Italy', true, true, 'VEGETARIANA', '€€€€', 'This old country house is the setting for some of the region’s most innovative cuisine. There’s no choice here, just one long surprise tasting menu with many courses that takes guests on a fast-paced and exciting culinary voyage. Although some of the dishes are inspired by Campanian traditions, the menu features flavours from around the world, recreating often little-known Italian and international recipes with a personalised twist. Chef Giuseppe Iannotti always succeeds in surprising his guests, thanks to his ingredients, cooking techniques and stunning presentations. A selection of wines from small-scale producers completes the picture – after all, Krèsios is simply another name for Bacchus.', 41.2045624, 14.5000207, 1);
INSERT INTO public.ristoranti VALUES (31, 'Il Piccolo Principe', 'piazza Giacomo Puccini 1, Viareggio, 55049, Italy', false, false, 'ITALIANA', '€€€€', 'Situated on the ground floor of the iconic Grand Hotel Principe di Piemonte, one of Versilia’s finest hotels, this gourmet restaurant boasts an elegant, contemporary-style dining room which has recently been extended into an exclusive wing adorned with works of art and bespoke designer furniture. Giuseppe Mancino is the name behind the success of this restaurant, a talented chef from Campania who delights his guests with his beautifully presented, “photogenic” cuisine. His dishes are creative and enticing, delicious and at the same time elegant – he manages to find the perfect balance between the fragrant flavours of Mediterranean cuisine and the precision of French technique. His dishes are showcased on three tasting menus, one of which is vegetarian, from which courses can be chosen individually à la carte style. The wine list is also excellent, proudly highlighting labels from Tuscany while at the same time including a selection of French options.', 43.8809756, 10.2355866, 1);
INSERT INTO public.ristoranti VALUES (32, 'Verso Capitaneo', 'piazza del Duomo 21, Milan, 20121, Italy', true, false, 'GIAPPONESE', '€€€€', 'The two Capitaneo brothers, united by their passion for cuisine yet with very different characters, have opened this restaurant in Piazza Duomo following years of experience working in Michelin-starred restaurants. In this informal ambience, guests have the option of dining either at black glass tables or at large benches arranged around the kitchen, from where they can observe the entertaining sight of the chef at work in the kitchen. The cuisine focuses on extremely fresh, top-quality ingredients showcased using unfussy techniques that put flavour centre stage. Exciting dishes include the blue lobster with yellow courgettes and the house “welcome” snack – an intriguing rose of beetroot petals and caviar, the latter one of the restaurant’s most featured posts on Instagram.', 45.4648103, 9.189585, 3);
INSERT INTO public.ristoranti VALUES (33, 'Antica Osteria Cera', 'via Marghera 24, Lughetto, 30010, Italy', false, false, 'AMERICANA', '€€€€', 'One of Italy’s most famous addresses for fish and seafood, this restaurant offers an extensive menu featuring classic house favourites alongside a growing list of more modern options. In this elegant, modern and minimalist-style setting (despite the name, don’t expect a trattoria-style ambience here!) enjoy raw fish dishes and grilled options alongside more traditional, often Venetian, specialities such as the Venetian-style spider crab, and classic Italian dishes such as the warm steamed fish salad and the fritto misto (mixed fried fish). In all dishes, the excellent quality of the ingredients shines through. There’s also an excellent wine list, with a particular focus on white wines.', 45.3881476, 12.1302222, 1);
INSERT INTO public.ristoranti VALUES (34, 'Antica Corona Reale', 'via Fossano 13, Cervere, 12040, Italy', true, false, 'INDIANA', '€€€€', 'Situated between the Langhe and Monviso, this long-established restaurant celebrated its 200th anniversary a few years ago. Run by the Vivalda family for five generations, the restaurant started out as a dairy farm before gaining a well-earned reputation for its cuisine. Owner-chef Gian Piero Vivalda (Passion Dessert Award 2024) creates top-quality menus featuring expertly prepared, colourful and aromatic dishes. Popular with food-lovers from Italy and abroad, Cervere is also a point of reference for many local businesses who supply the restaurant with capon, guinea fowl, veal, Carmagnola peppers, porcini mushrooms and much more besides. The menu offers an array of enticing flavours, with modern dishes featuring alongside classic favourites, including a delicate raviolo of bagna càuda served with legendary bouillabaisse, which has made a reappearance on the menu after guests’ insistent requests. In summer, dine alfresco in the shade of a beautiful pergola among colourful flowers and a small fountain. Two small private rooms are available for intimate dinners, one of which is in the wine cellar surrounded by legendary bottles of wine. There’s also a small shop selling cakes and biscuits.', 44.63505, 7.788635, 1);
INSERT INTO public.ristoranti VALUES (35, 'Andrea Aprea', 'corso Venezia 52, Milan, 20122, Italy', false, false, 'VEGANA', '€€€€', 'On the top floor of the Fondazione Luigi Rovati (housed in a magnificent historic building that is home to the Foundation’s Art Museum), talented chef Andrea Aprea has achieved his life-long dream with his eponymous restaurant. The setting is visually impressive, with a superb panoramic window boasting views of Porta Venezia park and Milan’s urban skyline. The large central dining room is dominated by a sparkling circular chandelier made from Murano glass and gold leaf, while the walls clad in black “bucchero” ceramics (from which the Etruscans used to make vases) lean slightly, directing the gaze towards the open-view kitchen. Here, guests can admire the chef and his team at work as they prepare the different dishes for the three tasting menus: Contemporaneità, a 5-course menu which explores the relationship between memory and innovation; Partenope, a 6-course menu focusing on specialities from Campania; and Signature, an extraordinary 8-course experience which expresses the chef’s culinary philosophy. Lastly, the palazzo’s hidden green courtyard at 52, Corso Venezia is home to the Caffè Bistrot where Andrea redefines family-style cuisine via a selection of classic favourites.', 45.4734602, 9.2042705, 3);
INSERT INTO public.ristoranti VALUES (36, 'Miramonti l''Altro', 'via Crosette 34, località Costorio, Concesio, 25062, Italy', true, false, 'VEGETARIANA', '€€€€', 'A French-Italian couple is at the helm in this attractive classic-style villa on the outskirts of Brescia, where a few tables have been laid out in the bay windows overlooking the garden. The friendly, experienced wife oversees the front of house, while her Breton husband is in the kitchen, where he recreates memories of his childhood in France through his use of French ingredients and culinary techniques. The menu also features more obviously Italian and Mediterranean dishes, all of which showcase the delicious, generous flavours that are the hallmark of the cuisine here. There is also an unforgettable cheese trolley with an excellent selection of cheeses in which Italy has the upper hand!', 45.6135819, 10.2043986, 3);
INSERT INTO public.ristoranti VALUES (37, 'Acquolina', 'via del Vantaggio 14, Rome, 00186, Italy', true, false, 'INDIANA', '€€€€', 'This modern, softly lit restaurant is situated in The First Roma hotel near Piazza del Popolo. With few decorations to distract the gaze and discreet, professional service, all the attention here is concentrated on Daniele Lippi’s cuisine. The chef creates two tasting menus – the first, shorter option focuses on fish dishes, while the second longer menu also includes a few meat options. Whichever you choose, you’ll enjoy creative cuisine which is also hearty, generous and full of substance, with a strong emphasis on aromatic herbs and a few barbecued dishes.', 41.9086474, 12.4753719, 3);
INSERT INTO public.ristoranti VALUES (38, 'D''O', 'piazza della Chiesa 14, loc. San Pietro all''Olmo, Cornaredo, 20007, Italy', true, false, 'MESSICANA', '€€€€', 'Two of the three dining rooms at this restaurant overlook a charming square with an elm tree and 17C church. After two decades of hard, painstaking work on his own, combined with years of experience elsewhere (including early spells with top chefs such as Marchesi and Ducasse), chef Davide Oldani has by now developed his own precise, recognisable style and is an established personality in the world of Italian cuisine. His creative dishes are rooted in Italian traditions and showcase superlative technique, beautiful presentation and convincing flavours. Year after year, this chef fine-tunes his “pop” cuisine with a real focus on detail, as demonstrated by the workshop he has created for his flour and yeast products. Our inspector particularly praised the warm and cold Grana Padano served with caramelised onions – an exciting interpretation of an iconic dish!', 45.48711, 9.01175, 3);
INSERT INTO public.ristoranti VALUES (39, 'L''Olivo', 'via Capodimonte 14, Anacapri, 80071, Italy', true, true, 'ITALIANA', '€€€€', 'This two-Michelin-starred restaurant is situated far from the crowded alleyways of Capri, in the greener and more residential Anacapri, where its backdrop is the semi-hidden Capri Palace, one of the island’s most luxurious hotels. Here, a large, elegant drawing room is the setting for Italian cuisine with a particular focus on Campania, with dishes which are occasionally reinterpreted with a modern twist and always brightly coloured and full of flavour. A real pleasure for the palate, with primi that are truly exploding with flavour (such as the eliche pasta with rock fish and the risotto with a Neapolitan ragu), chef Andrea Migliaccio’s cuisine is accompanied by impeccable and professional service.', 40.5559154, 14.2220085, 2);
INSERT INTO public.ristoranti VALUES (40, 'Magnolia', 'via Pelliciano 35, loc. Montilgallo, Longiano, 47020, Italy', true, false, 'ITALIANA', '€€€€', 'Situated in the elegant Relais Villa Margherita, an 18C villa converted into a stylish residence with just six guestrooms, verdant grounds and a swimming pool, Magnolia occupies a contemporary, veranda-style dining room with large picture windows boasting sweeping views of the Romagna hills as far as the mountainous “peak” of San Marino. Here, skilful chef Alberto Faccani serves a clever combination of the classic favourites that have marked his career, alongside other more unusual dishes that demonstrate a tireless search for experimentation. His contemporary style is elegant and balanced, as demonstrated by the delicate coconut milk sauce that provides the final flourish to his cuttlefish with caviar and peas.', 44.0731058, 12.3498464, 3);
INSERT INTO public.ristoranti VALUES (41, 'Piazzetta Milù', 'corso Alcide De Gasperi 23, Castellammare di Stabia, 80053, Italy', true, false, 'CINESE', '€€€€', 'Champagne enthusiasts will be in their element here, thanks to a wine list (presented on a tablet) that features almost 5 000 labels. Emanuele oversees the wine selection with great enthusiasm, introducing guests to his world of small-scale wineries with a real ability to find something to suit every palate. Your dining experience begins in the wine cellar, where the first part of your meal is served in an enchanting setting surrounded by some of the world’s best wines. The whole family is involved in running this restaurant, which started out as a pizzeria and has since become one of the region’s best addresses thanks to the passion and dedication of the latest generation. Chef Maicol creates dishes from Campania as well as exotic fare from much further afield, ably assisted by his brothers Valerio and Emanuele front of house.', 40.7018717, 14.4829218, 3);
INSERT INTO public.ristoranti VALUES (42, 'Villa Elena', 'via San Vigilio 56, Bergamo, 24129, Italy', true, true, 'FAST_FOOD', '€€€€', 'Situated near the Città Alta in a delightful setting surrounded by hills, Villa Elena is one of the most sumptuous villas in the countryside around Bergamo. Housed in a 16C building with a medieval tower and a terrace-cum-garden, the restaurant boasts a stunning interior decor of stucco, marble, mirrors and frescoes. This luxurious ambience is more than equalled by the fine cuisine created by Marco Galtarossa in partnership with Enrico Bartolini (the Italian chef with the largest number of Michelin stars). The occasionally elaborate dishes are sometimes divided into several courses, and combined with a clever use of aromatic herbs, all of which makes this the perfect choice for a memorable meal and special occasion.', 45.7105439, 9.648062, 2);
INSERT INTO public.ristoranti VALUES (43, 'George Restaurant', 'corso Vittorio Emanuele 135, Naples, 80121, Italy', true, false, 'AMERICANA', '€€€€', 'This roof-garden restaurant in one of Naples’ most luxurious hotels (Grand Hotel Parker’s) boasts an open-view kitchen facing a breathtaking panorama that takes in Vesuvius, the Bay of Naples and the city itself, which extends below the hotel in an evocative display of sparkling lights. It’s a challenge for the cuisine to compete with so much beauty but young chef Domenico Candela is more than equal to the task. His cuisine showcases the culinary specialities of the city and further afield with extraordinary skill, combining superb produce and recipes from Campania with techniques learnt in France to produce truly remarkable reinterpretations of regional dishes.', 40.8372677, 14.2300686, 1);
INSERT INTO public.ristoranti VALUES (44, 'O Me O Il Mare', 'Via Roma 45/47, Gragnano, 80054, Italy', false, false, 'VEGETARIANA', '€€€€', 'Known around the world as the town of pasta, Gragnano is still home to small-scale pasta-makers renowned for their top-quality pasta. To reinforce this fact, this restaurant is housed in a building (dating back to 1695) once used as pasta factory. Now boasting a modern, spacious dining room with a vaulted ceiling and open-view kitchen, the restaurant serves three tasting menus, all with strong links to the region but also featuring more creative touches. The region also takes pride of place on the wine list – it’s worth asking the talented and experienced sommelier for her recommendations.', 40.6916293, 14.5157334, 1);
INSERT INTO public.ristoranti VALUES (45, 'La Buca', 'corso Garibaldi 45, Cesenatico, 47042, Italy', false, true, 'FAST_FOOD', '€€€', 'Choose a table on the outdoor summer terrace (right over the water!) at this restaurant in order to best appreciate its location overlooking the picturesque canal port and its period houses. The indoor dining room is also attractive, with its open-view kitchen and modern and elegant feel, while the menu focuses almost exclusively on fish, often served with vegetables, some of which are organic. Enjoy a wide selection of raw antipasti to start (some simple in their preparation, while others are more elaborate), then choose from an array of beautifully presented, modern dishes, such as stuffed mullet with pickled plums and lemon salad, perhaps accompanied by one of the many champagnes included on the wine list.', 44.200314, 12.396823, 2);
INSERT INTO public.ristoranti VALUES (46, 'LoRo', 'via Bruse 2, Trescore Balneario, 24069, Italy', false, true, 'CINESE', '€€€', 'The cuisine served at LoRo is imaginative both in its presentation and its ingredients, which are combined in light, original and healthy (in the best sense of the word) dishes. The focus here is on fish and seafood, especially in the antipasti and primi courses, while all the dishes are listed with imaginative names on the menu. Chef Pierantonio Rocchetti reinterprets classic Italian favourites with flair and imagination, serving generous portions that do not skimp on flavour and taking guests on a delicious culinary journey that culminates in his excellent desserts. The restaurant’s “Sala Lab” is home to a large designer-style table that can be transformed to accommodate different numbers of guests, allowing the chef to prepare his dishes directly at the table in an ambience which is friendly and convivial while still maintaining an elegant feel.', 45.6938611, 9.8324198, 3);
INSERT INTO public.ristoranti VALUES (47, 'Casin del Gamba', 'via Roccolo Pizzati 1, Altissimo, 36070, Italy', true, false, 'INDIANA', '€€€€', 'The journey to get here – a winding road through woods and hills – may be challenging at times but the warm welcome offered by the whole family Dal Lago at this delightful restaurant makes you feel completely at home and more than compensates for the effort. Owner-chef Antonio shares the honours and duties of his role with long-established sous-chef Biolo. Together, they prepare cuisine that is perfectly balanced between classic flavours and modern trends, using local ingredients that respect the passing seasons. Game features on the menu in winter, while dishes are often seasoned with wild aromatic herbs (for example, the local snails served with thyme and onion bread). For her part, Signora Daria determinedly takes on two roles: she not only prepares the desserts, but also skilfully supervises front of house, ably assisted by son Luca who is happy to advise guests on their choice of wine. The well-structured wine list also includes a good number of organic wines.', 45.6178, 11.2615, 3);
INSERT INTO public.ristoranti VALUES (48, 'Kitchen', 'via per Cernobbio 41/a, Como, 22100, Italy', true, true, 'INDIANA', '€€€', 'Nestled amid the greenery of a private park, Kitchen is an elegant restaurant which serves creative Italian cuisine with a focus on seasonal ingredients and a perfect balance between produce, technique and flavour. The chef uses herbs and vegetables from the restaurant’s own biodynamic kitchen garden which can be seen in front of the entrance. This natural bounty provides the basis for the Green tasting menu; the other tasting menu is called Experience; there’s also an excellent à la carte. Service is attentive plus there’s an excellent selection of wines.', 45.8334043, 9.0715676, 2);
INSERT INTO public.ristoranti VALUES (49, 'Ancòra', 'viale Trento 31, Cesenatico, 47042, Italy', true, true, 'GIAPPONESE', '€€€', 'A new adventure for skilful chef Agostino Iacobucci (his original restaurant of the same name is in Castel Maggiore), housed within a villa that food-enthusiasts will remember as the former home of the two-Michelin-star Magnolia. In this elegant and welcoming setting, resident chef Marco Garattoni demonstrates the precise culinary techniques acquired during his many years working in top-quality restaurants. His dishes are contemporary, always colourful, beautifully presented, pleasing and attractive, even mouthwatering at times, and mostly based on fish, with the addition of a few vegetarian and meat options. Don’t miss one of this Neapolitan chef’s most famous signature dishes, namely his “babà a tre lievitazioni”, which is light, delicious and perfect in every way!', 44.1955658, 12.4042192, 3);
INSERT INTO public.ristoranti VALUES (50, 'Abbruzzino Oltre', 'Piazza Salvo d''Acquisto 16, Lamezia Terme, 88046, Italy', false, false, 'VEGANA', '€€€€', 'This restaurant, the new home of young chef Luca Abbruzzino, occupies the first floor of a historic palazzo in the town centre which has recently been converted into a small hotel offering six exclusive guestrooms. Guests can enjoy an aperitif in the elegant small lounge before making their way to one of the two dining rooms with just five tables in total (all ellipsoid in shape), where the chef’s surprise tasting menu is served. Featuring several small courses, the menu showcases imaginative and skilfully prepared dishes that demonstrate the chef’s love for his native region. We particularly enjoyed the dry-aged angler fish with black sesame (already renowned as one of the chef’s classics), spring onion, sultanas and anchovy sauce; the spaghetti with mullet, orange, turmeric and “nduja” sauce; and the pigeon with peach, tomato and barley. Although wine-paring options are available, you can also ask the talented and enthusiastic maître-sommelier to recommend a bottle or even simply a glass.', 38.9770969, 16.3202202, 3);
INSERT INTO public.ristoranti VALUES (51, 'Abbruzzino', 'via Fiume Savuto, località Santo Janni, Catanzaro, 88100, Italy', true, false, 'VEGETARIANA', '€€€', 'Having opened new premises in Lamezia Terme (Abbruzzino Oltre), this restaurant has retained young chef Antonio Fazio (who practically grew up here) at the helm at this address, where he continues to offer dishes that perfectly combine creativity with Calabrian traditions. This remains an excellent choice for anyone in search of regional cuisine reinterpreted with a contemporary twist. Front of house, the service overseen by the chef’s parents Antonio and Rosa is both friendly and professional. The impressive wine list is also influenced by the family’s love for the region, with one section completely dedicated to local labels, and another that focuses on wines from elsewhere in Italy and further afield. We particularly enjoyed the many delicious appetisers, as well as the rice with peas, pecorino and oysters, and the house signature dessert (bread, oil and sugar), which always features on the menu. Choose from two surprise tasting menus and a small à la carte.', 38.8901852, 16.6236902, 1);


--
-- TOC entry 5035 (class 0 OID 16619)
-- Dependencies: 220
-- Data for Name: utenti; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.utenti VALUES (1, 'Carlo', 'Cracco', 'carlo', '976c49391de9909cda71c0b17f580f9e9c58b6264516ce8466ebd10c24caf0a2', '1965-10-08', 'Galleria Vittorio Emanuele Secondo, Via Giovanni Berchet, Duomo, Municipio 1, Milano, Lombardia, 20122, Italia', 'RISTORATORE', 45.4656515, 9.1900113);
INSERT INTO public.utenti VALUES (2, 'Bruno', 'Barbieri', 'bruno', 'ccc68482d9e0eee0789e64c7674421076738f8836857ea89bcd0afb832bf3fc3', '1962-01-12', '2, Piazza Umanitaria, Guastalla, Municipio 1, Milano, Lombardia, 20122, Italia', 'RISTORATORE', 45.4585926, 9.2006009);
INSERT INTO public.utenti VALUES (3, 'Joseph', 'Bastianich', 'joe', '78675cc176081372c43abab3ea9fb70c74381eb02dc6e93fb6d44d161da6eeb3', '1968-09-17', '94, Corso di Porta Romana, Guastalla, Municipio 1, Milano, Lombardia, 20122, Italia', 'RISTORATORE', 45.4555681, 9.1964716);
INSERT INTO public.utenti VALUES (4, 'Antonino', 'Cannavacciuolo', 'antonino', '79395ca0a631c4e0a6432c726929f105f097c7c70193ade04192418c7d839392', '1975-04-16', 'Villa Crespi, 18, Via Giuseppe Fava, Legro, Orta San Giulio, Novara, Piemonte, 28016, Italia', 'CLIENTE', 45.7963733, 8.4161322);


--
-- TOC entry 5047 (class 0 OID 0)
-- Dependencies: 225
-- Name: recensioni_id_recensione_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recensioni_id_recensione_seq', 1, true);


--
-- TOC entry 5048 (class 0 OID 0)
-- Dependencies: 221
-- Name: ristoranti_id_ristorante_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ristoranti_id_ristorante_seq', 51, true);


--
-- TOC entry 5049 (class 0 OID 0)
-- Dependencies: 219
-- Name: utenti_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.utenti_id_seq', 1, false);


--
-- TOC entry 4881 (class 2606 OID 24879)
-- Name: preferiti preferiti_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preferiti
    ADD CONSTRAINT preferiti_pk PRIMARY KEY (id_cliente, id_ristorante);


--
-- TOC entry 4877 (class 2606 OID 24894)
-- Name: recensioni recensioni_cliente_ristorante_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recensioni
    ADD CONSTRAINT recensioni_cliente_ristorante_unique UNIQUE (id_cliente, id_ristorante);


--
-- TOC entry 4879 (class 2606 OID 24862)
-- Name: recensioni recensioni_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recensioni
    ADD CONSTRAINT recensioni_pk PRIMARY KEY (id_recensione);


--
-- TOC entry 4875 (class 2606 OID 24836)
-- Name: ristoranti ristoranti_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ristoranti
    ADD CONSTRAINT ristoranti_pk PRIMARY KEY (id_ristorante);


--
-- TOC entry 4871 (class 2606 OID 24816)
-- Name: utenti utenti_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utenti
    ADD CONSTRAINT utenti_pk PRIMARY KEY (id_utente);


--
-- TOC entry 4873 (class 2606 OID 24892)
-- Name: utenti utenti_username_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utenti
    ADD CONSTRAINT utenti_username_unique UNIQUE (username);


--
-- TOC entry 4885 (class 2606 OID 24880)
-- Name: preferiti preferiti_ristoranti_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preferiti
    ADD CONSTRAINT preferiti_ristoranti_fk FOREIGN KEY (id_ristorante) REFERENCES public.ristoranti(id_ristorante);


--
-- TOC entry 4886 (class 2606 OID 24885)
-- Name: preferiti preferiti_utenti_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preferiti
    ADD CONSTRAINT preferiti_utenti_fk FOREIGN KEY (id_cliente) REFERENCES public.utenti(id_utente);


--
-- TOC entry 4883 (class 2606 OID 24863)
-- Name: recensioni recensioni_ristoranti_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recensioni
    ADD CONSTRAINT recensioni_ristoranti_fk FOREIGN KEY (id_ristorante) REFERENCES public.ristoranti(id_ristorante) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4884 (class 2606 OID 24868)
-- Name: recensioni recensioni_utenti_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recensioni
    ADD CONSTRAINT recensioni_utenti_fk FOREIGN KEY (id_cliente) REFERENCES public.utenti(id_utente) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4882 (class 2606 OID 24837)
-- Name: ristoranti ristoranti_utenti_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ristoranti
    ADD CONSTRAINT ristoranti_utenti_fk FOREIGN KEY (proprietario) REFERENCES public.utenti(id_utente) ON UPDATE CASCADE ON DELETE CASCADE;


SELECT setval('public.utenti_id_seq', (SELECT MAX(id_utente) FROM public.utenti));


-- Completed on 2026-07-31 16:49:28

--
-- PostgreSQL database dump complete
--
