---
id: 4ec1fda2-79e7-446a-b3f6-4f890187a5fd
---
sequenceDiagram
    actor Admin
    participant PA as PannelloAdmin
    participant DB@{ "type": "database" } as DatabaseTK


    Admin->>+PA: avvia applicazione
    create participant SC as ServerContext
    PA->>+SC: avvia applicazione

    create participant MDB as ManagerDB
    SC->>MDB: create

    create participant auth as AuthServiceImp
    SC->>auth: create
    create participant recensioni as RecensioniServiceImp
    SC->>recensioni: create
    create participant ristoranti as RistorantiServiceImp
    SC->>ristoranti: create
    create participant profilo as ProfiloServiceImp
    SC->>profilo: create
    create participant preferiti as PreferitiServiceImp
    SC->>preferiti: create

    SC-->>-PA: caricamento completato
    PA-->>Admin: caricamento completato

    Admin->>PA: inserisce credenziali database
    PA->>+MDB: connetti(credenziali)
    MDB->>+DB: connetti
    DB-->>-MDB: connessione OK
    MDB-->>-PA: database connesso
    PA-->>Admin: database connesso

    Admin->>PA: avvia server
    create participant STK as ServerTK
    PA->>+STK: avviaServer(serverContext)

    create participant Registry
    STK->>Registry: crea registro

    STK->>Registry: rebind(AuthServiceImp)
    STK->>Registry: rebind(RecensioniServiceImp)
    STK->>Registry: rebind(RistorantiServiceImp)
    STK->>Registry: rebind(ProfiloServiceImp)
    STK->>Registry: rebind(PreferitiServiceImp)

    STK-->>-PA: server pronto
    PA-->>-Admin: server pronto